name: RucoCop

on:
  push:
    branches: [master]
    paths-ignore:
      - '*.md'
      - 'lib/fluent/version.rb'
  pull_request:
    branches: [master]
    paths-ignore:
      - '*.md'
      - 'lib/fluent/version.rb'
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  rubocop:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.4']
    name: Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1.245.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          bundle install
          gem install benchmark-ips
      - name: Run RuboCop
        run: rubocop
